### ISSUE TITLE
Room list: Loosely related performance investigations

### ISSUE THREAD

**Issue by turt2live** [element-hq/element-web#14664]
Things that people mention in the context of the room list but aren't directly related to the room list:
* [ ] https://github.com/vector-im/riot-web/issues/14574 - Room switching time is slow [due to timeline]
* [x] https://github.com/vector-im/riot-web/issues/14639 - CIDER is slow on room switch
* [x] https://github.com/vector-im/riot-web/issues/14694 - Room notification counts are slow
* [x] https://github.com/vector-im/element-web/issues/14750

**Comment by t3chguy** [comment]
Fixed by new room list
