### ISSUE TITLE
Implement Knocking on Element Web

### ISSUE THREAD

**Issue by jakewb-b** [element-hq/element-web#18655]
Links
- PRD (internal): https://docs.google.com/document/d/15ornTrYI5UYVkvlHcD89IIhYIKvdfZcPn6V-KVnMmx8/edit
- Spec: https://spec.matrix.org/v1.2/client-server-api/#knocking-on-rooms
- Figma designs: https://www.figma.com/file/7TqjqdMBaPpm3IavKsMYu6/%5BBWI%5D-Knocking?type=design&node-id=367-50166&mode=design&t=6Bjqu0KINaAjkbV0-0
- Screenshots of proposed design: https://github.com/vector-im/element-web/issues/18655#issuecomment-1095528465 (superceded by Figma??)
- Already implemented by Synapse, just need UI

Mobile (out of scope for this issue): See https://github.com/vector-im/element-android/issues/3875 and https://github.com/vector-im/element-ios/issues/4731
```[tasklist]
### Tasks
- [ ] https://github.com/vector-im/element-web/issues/26043
- [ ] https://github.com/vector-im/element-web/issues/26044
- [ ] https://github.com/vector-im/element-web/issues/26083
- [ ] https://github.com/vector-im/element-web/issues/26084
- [ ] https://github.com/matrix-org/synapse/issues/16307
- [ ] https://github.com/element-hq/element-web/issues/27025
```

**Comment by Mikaela** [comment]
I am unable to open either of the links from the original submission and am wondering whether it's noted that this is part of Matrix protocol specification version 1.1?

* https://spec.matrix.org/v1.1/rooms/v7/

**Comment by turt2live** [comment]
Screenshots of the designs for inspiration (in no particular order):
![ModeratorView](https://user-images.githubusercontent.com/1190097/162825331-feded7a6-70b7-478e-af0e-ea3a51272b22.png)
![RequestSent](https://user-images.githubusercontent.com/1190097/162825335-a6acab89-1294-47aa-877e-aabcb6189225.png)
![RequestToJoin](https://user-images.githubusercontent.com/1190097/162825336-f86b1be3-992d-42fc-94d8-4494cf5ac272.png)
![CreateKnockableRoom](https://user-images.githubusercontent.com/1190097/162825342-b626f773-99ce-4bb6-a66c-2ebdb8fc5c9b.png)

**Comment by t3chguy** [comment]
> I was wondering, why would you move the "People" tab to settings instead of leaving it in the side panel and adding a new category for Access Requests in the same way as there is a category for invited people already?

Its not moved, the People right panel card remains, just won't show knocks to prevent noise/spam.

Settings already has a people section (people with non-default power levels) - this just extends that list.

<img width="1060" alt="image" src="https://user-images.githubusercontent.com/2403652/162919807-c760059f-5f06-4e38-90c8-22d808b1145b.png">

**Comment by enekonieto** [comment]
Would it be interesting if members with enough privileges see the knock in the timeline?

**Comment by Mikaela** [comment]
If I understand correctly, everyone in the room will see the knocking as it's a membership event, unless Element Web especially hides that (which I imagine would then be visible through /devtools or another client). To answer the knock necessary PL is the one to invite or kick (or ban)

**Comment by enekonieto** [comment]
I think the event in the timeline should have the Accept/Reject buttons for users with enough PL. I comment this because I don't see the timeline in the prototype sent by @turt2live.

**Comment by Mikaela** [comment]
Does this issue include that when join rule is set to `knock` or `knock_restricted`, Element Web settings "who can join this room" has radio button menu with nothing checked? Or does `knock_restricted` need a new issue?

My room versions are 9 and 10.

**Comment by turt2live** [comment]
It would be a later stage of development

**Comment by Mikaela** [comment]
The previous time I used knocking was yesterday when we bridged an ICT team from Telegram to Matrix. We couldn't use restricted as that would have required us to already have a room with everyone and due to the room's nature we couldn't make it fully public.

I am also utilising `knock_restricted` in my personal rooms a lot.

Thus I would like to ask if there has been any progress with supporting knocking in Elements as it's a feature of Matrix Spec 1.1 with Matrix Spec 1.5 being around the coner? https://github.com/matrix-org/matrix-spec/issues/1337

**Comment by turt2live** [comment]
Knocking is still low on the list of priorities. Due to scheduling, we're expecting to make more forward progress next summer.

**Comment by Mikaela** [comment]
Thanks for the update, I am happy to hear that knocking is on the list of priorities even if not that high on it

**Comment by ArtexJay** [comment]
This would be an excellent tool for Spaces/Rooms to help lock down or secure their communities.

**Comment by BurnyBoi** [comment]
> This would be an excellent tool for Spaces/Rooms to help lock down or secure their communities.

was just thinking to ask: does the design proposed above have knocking on spaces in mind?

**Comment by ninja85a** [comment]
> > This would be an excellent tool for Spaces/Rooms to help lock down or secure their communities.
> 
> was just thinking to ask: does the design proposed above have knocking on spaces in mind?

spaces are just rooms so I dont see why they wouldnt support knocking

**Comment by Xiretza** [comment]
> spaces are just rooms so I dont see why they wouldnt support knocking

Spaces don't have a timeline unless you enable developer tools, so any design that would show knocks in the timeline would not work for spaces without special handling.

**Comment by ninja85a** [comment]
> > spaces are just rooms so I dont see why they wouldnt support knocking
> 
> Spaces don't have a timeline unless you enable developer tools, so any design that would show knocks in the timeline would not work for spaces without special handling.

thats true

**Comment by Mikaela** [comment]
Due to Matrix Foundation considering _publicly joinable members-only history_ rooms as free to be published on their website, I would like to ask whether knocking in Elements (https://github.com/vector-im/element-meta/issues/43) is still expected to make more forward progress this summer?

- https://github.com/matrix-org/matrix-public-archive/blob/main/docs/faq.md#why-does-the-archive-user-join-rooms-instead-of-browsing-them-as-a-guest
- https://github.com/matrix-org/matrix-public-archive/issues/47#ref-issue-1729509198

**Comment by turt2live** [comment]
Element unfortunately does not have plans to make progress this summer on knocking. I'll include the latest design screenshots below, if someone is interested in writing a PR for the feature. Some of this work may already be done by https://github.com/matrix-org/matrix-react-sdk/pull/9093 - feel free to use it as a base.

![Create Room Dialog](https://github.com/vector-im/element-web/assets/1190097/ec86b8ec-e0ed-4a33-931c-0c25fe525d60)
![Knocking - Ask to join](https://github.com/vector-im/element-web/assets/1190097/5e68e3bb-1640-4239-a59f-32b66a899cb3)
![Knocking - request to join sent](https://github.com/vector-im/element-web/assets/1190097/629fa50f-c9b0-4568-92ec-afd3f511b60b)
![Cancel request to join](https://github.com/vector-im/element-web/assets/1190097/0237d5a2-ffd4-4478-a7ea-b1f29dcd0a02)
<img width="1440" alt="Knocking - denied access" src="https://github.com/vector-im/element-web/assets/1190097/48a838ca-27d8-44c7-97f2-e15a0b44a6ca">
![One Request - with message](https://github.com/vector-im/element-web/assets/1190097/2899a7c9-3a4f-4371-90f6-9e3da8c829d6)
(if no message attached to request, don't show "View Message" button)
![Knocking - more than 3 people asking to join](https://github.com/vector-im/element-web/assets/1190097/49a9829c-0ce5-48b4-8857-ae7b852c7915)
![Room Settings - Manage knocks](https://github.com/vector-im/element-web/assets/1190097/48828a70-2e02-4021-9260-e76b164a198c)
![Join Settings - Room](https://github.com/vector-im/element-web/assets/1190097/33f2d94a-50b0-402e-ad9e-86e8c98e6e4e)

**Comment by dhenneke** [comment]
Info: We from @nordeck are starting to implement this feature. So you should be seeing the first PRs from us in the next couple of weeks.

**Comment by nao9797** [comment]
I have been very thankful for the very existence of Element thus far, but I feel that the current options are extremely limiting and in reality it only boils down to 2 options:
A. Invite People manually if you want a private room. 
B. Host a public room/space 

For someone like myself who dedicated time to helping bring consciousness about the best FOSS apps through various methods, this is creating a major gap in potential. I think allowing knocking should be a priority if Element wants to increase its user base / popularity. 

Imagine this scenario: Assume a YouTuber wants to host a private space and they have 100 Followers. The user is concerned about trolls and unknown people joining. He knows he only has 100 Followers and he wants nothing more than for his followers to become aware of the existence of Element by only simply providing a link to the private room, encouraging them to create an account in order to join the private room with the hopes that they may sooner dump other chatting platforms that don't provide the beautiful features Element does. This would help raise consciousness about Element as a chatting platform alternative and thus increase its popularity more efficiently. 

Please consider this if you don't think Knocking should be Top Priority. At least you will understand the potential it could unleash is very great. I would add to the suggestion to include adding a few text input fields with labels so that the author/host can ask for a reference. 
Example: In the section for enabling Knocking in the settings, allow the Host to add Fields for Askers to Answer a Question. 

Question 1: Enter Label / Question:
[What is your YouTube Username?]

Question 2: 
[What is your interest?]

The idea is to make it easier for Hosts to question the askers in order to have a reference to identify them or make sure the intention of the asker is understood. 

I think you for taking the time to read this and for all work that has been done so far on Element! 
Namaste!

**Comment by rettichschnidi** [comment]
Tried the current state, and seems very well done to me. Thanks!

Regarding spaces: Are there any ideas/plans on making knocking work for them too? As of Element Web 1.11.46, I can enable knocking for spaces, and users can knock, but the admin of the space does not get a notification about the request.

**Comment by Sun-Laura** [comment]
As mentioned some months ago we contributed to the knocking feature for the past few weeks. Our focus is still the implementation in the rooms.
As you @rettichschnidi mentioned, the knocking for spaces might be also a great value. Despite this it is not our focus yet, maybe Element itself has a more concrete plan for spaces or someone else can take over to contribute. ;)
