### ISSUE TITLE
Consolidated requirements for voice message audio queue

### ISSUE THREAD

**Issue by turt2live** [element-hq/element-web#18804]
*These are developer notes*

Issues:
* https://github.com/vector-im/element-web/issues/18715
* https://github.com/vector-im/element-web/issues/18714
* https://github.com/vector-im/element-web/issues/17961

Requirements for the system:
* [ ] Track where each event tile was left off at during playback
* [ ] Maintain an ordered set of voice messages (timeline order) to progress playback
* [ ] Maintain ordered set of actions (for A.5 -> B -> A -> C playback)

Product requirements:
* Navigating away from a room pauses playback (position remembered)
* Returning to a room and pressing play starts from where the user left off at before (which may be the start)
* When a voice message finishes playing, the next voice message starts playing
* If the user plays another voice message while another is playing, it pauses the current voice message and plays through.
  * This is "A.5 -> B -> A -> C" playback. In a case of 3 voice messages, ordered A, B, and C, the user can start playing A, interrupt it with B, and when B finishes the audio will return to A to play through, then to C to finish it off. If the user didn't interrupt anything then it'll be A -> B -> C.
* Should persist across restarts

System design: TBD
