### ISSUE TITLE
Tighten the What's New > Changelog > Update flow and roll it out to more than Develop

### ISSUE THREAD

**Issue by daniellekirkwood** [element-hq/element-web#26092]
![image](https://github.com/vector-im/element-web/assets/89144281/f72332ea-9f27-43ce-80a0-1dc9814b9135)

We have this in Develop only. I'd like us to polish it and consider rolling it out for other versions (Nightly, Web, & Desktop)

We need to discuss this more (and especially where it lands on our priorities list but...) I'd like to: 

```[tasklist]
### Tasks
- [ ] Make the button on the left a secondary button and have it open the changelog
- [ ] Make the button on the right the primary button and have it take users straight to upgrade
- [ ] Update the layout of the changelog dialog so that it's easier to read
- [ ] Implement a changelog process internally where these are written as release notes, not links to GH tickets
- [ ] Discuss rolling it out on other versions of our product suite
- [ ] Discuss how ESS users might be able to change or tailor the content
```

**Comment by t3chguy** [comment]
Would also need updates to the backend infrastructure running the show here, right now is only works for commit ranges (develop) not nightly versions or stable production versions.

**Comment by daniellekirkwood** [comment]
Does that ☝️ block us from making the polish changes listed or just a note as part of the "roll out to other versions" discussion point? @t3chguy

**Comment by t3chguy** [comment]
It blocks

> roll it out to more than Develop

and 

> Implement a changelog process internally where these are written as release notes, not links to GH tickets

as currently it is just a proxy of the Github `/commits` API.

**Comment by gdt** [comment]
The most important thing is to show the user the version that is running now and the new version.   I find a changelog without a version to be strange.
