### ISSUE TITLE
Element-R: "Migrate to rust" labs button

### ISSUE THREAD

**Issue by richvdh** [element-hq/element-web#26678]
At some point we will need to start actively migrating people who are using EW sessions on legacy Crypto to Rust crypto.

We will need a migration process for this. To gain confidence in the migration, we will add some sort of "developer feature" where people can request a migration. Later, we will automate the migration.
```[tasklist]
### Tasks
- [ ] https://github.com/matrix-org/matrix-rust-sdk-crypto-wasm/issues/78
- [ ] https://github.com/matrix-org/matrix-js-sdk/issues/3963
- [ ] https://github.com/matrix-org/matrix-js-sdk/issues/3964
- [ ] https://github.com/element-hq/element-web/issues/26772
- [ ] https://github.com/element-hq/element-web/issues/26773
- [ ] https://github.com/element-hq/element-web/issues/26894
- [ ] https://github.com/element-hq/element-web/issues/26820
```

**Comment by richvdh** [comment]
Some thoughts on how to achieve this:

1. The FFI bindings have a [bunch of code](https://github.com/matrix-org/matrix-rust-sdk/blob/a262cb2/bindings/matrix-sdk-crypto-ffi/src/lib.rs#L60-L545) to take libolm-pickled objects and store them in a matrix-rust-sdk `CryptoStore`.  I think we need to push as much of this as we can down to `matrix-sdk-crypto`, and then expose it in the wasm bindings.

1. We make the "Rust cryptography implementation" button turn-on-able. (Currently, it is always disabled; change it to only be disabled when the feature is on; see `RustCryptoSdkController`.) We also make it reload the app when it is switched on; see `ReloadOnChangeController` for examples of how to do this. Some changes needed to the wording on the button.

   This means that, once we restart, `MatrixClientPeg.initClientCrypto` will find `useRustCrypto` is `true`, causing it to call `MatrixClient.initRustCrypto` instead of `MatrixClient.initCrypto`. (This will be much the same codepath as when we drop legacy crypto support, which is good.) 

1. In `MatrixClient.initRustCrypto`, we perform the migration. First of all, we need to decide if there might be data to migrate. We should add a method to `js-matrix-sdk`'s `CryptoStore` which can do this check (probably using the existing `exists` static methods in `IndexedDBCryptoStore` and `LocalStorageCryptoStore`). If it does, we call `await this.cryptoStore.startup()`, and then carry on with the rest of the migration....

TODO

**Comment by richvdh** [comment]
Looking at the performance of this as it stands:

On a test database containing 37 olm sessions and 4810 megolm sessions:

* 10.181s: migration start: counting the sessions to be imported
* 10.202s: start importing base data
* 10.267s: start importing olm sessions
* 10.363s: start importing megolm sessions
* 22.843s: migration complete

Obviously, that is dominated by the megolm session import, at 12.5s for 4810 sessions, or ~130ms for each batch of 50 sessions. The actual time for each batch is quite variable, but there are three stages:
 * Read a batch of sessions from the legacy db. Average time: 19.0ms
 * Save batch to new db. Average time: 34.1ms
 * Delete the batch from the legacy db. Average time: 77.3ms.

Somewhat unexpected that deleting things from the old db is what takes the time. We could improve it by (empirically) about 20% by iterating through the store looking for rows to delete; or we could rewrite the whole thing to store the progress made so far and delete everything on a single batch at the end. Not sure it is worthwhile though. If we need it to go faster, we can do it in the background.
