### ISSUE TITLE
 Use Compound tooltip component for all tooltips in EW

### ISSUE THREAD

**Issue by langleyd** [element-hq/element-web#26762]
#### What would you like to do?
 Replace all existing tooltip occurrences with the tooltip in [Compound](https://github.com/element-hq/compound)

#### Why would you like to do it?
The existing tooltip is is accessible and the compound tooltip [is being made accessible](https://github.com/vector-im/compound/issues/248).

#### How would you like to achieve it?
Replace tooltip occurrences 1 by 1, improving the compound tooltip or adapting the site of it's usage with support from design/product, as necessary.

```[tasklist]
### Tasks
- [x] https://github.com/element-hq/compound-web/pull/156
- [x] https://github.com/matrix-org/matrix-react-sdk/pull/12416
- [ ] https://github.com/matrix-org/matrix-react-sdk/pull/12443
- [ ] https://github.com/matrix-org/matrix-react-sdk/pull/12456
- [ ] https://github.com/matrix-org/matrix-react-sdk/pull/12455
- [ ] https://github.com/matrix-org/matrix-react-sdk/pull/12458
- [ ] https://github.com/matrix-org/matrix-react-sdk/pull/12459
- [ ] https://github.com/matrix-org/matrix-react-sdk/pull/12460
- [ ] https://github.com/matrix-org/matrix-react-sdk/pull/12461
- [ ] https://github.com/matrix-org/matrix-react-sdk/pull/12462
- [ ] https://github.com/matrix-org/matrix-react-sdk/pull/12487
- [ ] https://github.com/matrix-org/matrix-react-sdk/pull/12489
- [ ] https://github.com/matrix-org/matrix-react-sdk/pull/12490
- [ ] https://github.com/matrix-org/matrix-react-sdk/pull/12493
- [ ] https://github.com/matrix-org/matrix-react-sdk/pull/12497
- [ ] https://github.com/element-hq/compound-web/pull/165
- [ ] https://github.com/matrix-org/matrix-react-sdk/pull/12522
- [ ] https://github.com/matrix-org/matrix-react-sdk/pull/12525
- [ ] https://github.com/matrix-org/matrix-react-sdk/pull/12539
- [ ] https://github.com/matrix-org/matrix-react-sdk/pull/12542
- [ ] https://github.com/matrix-org/matrix-react-sdk/pull/12549
```

**Comment by gaelledel** [comment]
@nadonomy This is the issue we're discussing with @t3chguy
