### ISSUE TITLE
Compound color refinements

### ISSUE THREAD

**Issue by robintown** [element-hq/element-web#26992]
Element Web is using colors from Compound, but since these were originally applied on a [best-effort basis](https://github.com/element-hq/element-web/issues/25547), we're finding that their usage does not always match their intended semantics. This is particularly relevant for users of custom themes, who may see unexpected results where we've applied the wrong semantic color tokens. Additionally, as we continue to integrate more Compound components into Element Web, we could stand to improve Element Web's visual coherency by updating the colors of some existing components.

@gaelledel and I have paired to review Element Web's color usage, and we discovered a number of things that we'd like to revise ([Figma](https://www.figma.com/file/pqhlirZFEwEp5XpudSbiia/Theming-Web-templates?type=design&node-id=75-37203&mode=design&t=WcHeawAn86kjcXx5-0)). As with the original color pass, these are to be incremental improvements, as we can't realistically check every variation of every component.

```[tasklist]
### Tasks
- [x] Message bubble background colors https://github.com/matrix-org/matrix-react-sdk/pull/12343
- [x] Pill background colors https://github.com/matrix-org/matrix-react-sdk/pull/12343
- [x] Message sent icon color https://github.com/matrix-org/matrix-react-sdk/pull/12343
- [x] Jump to bottom / jump to unread button colors https://github.com/matrix-org/matrix-react-sdk/pull/12343
- [x] Composer placeholder text color https://github.com/matrix-org/matrix-react-sdk/pull/12343
- [x] Menus - their background color, icon colors, and border https://github.com/matrix-org/matrix-react-sdk/pull/12332
- [x] Quick settings (multiple changes) https://github.com/matrix-org/matrix-react-sdk/pull/12332
- [x] Colors of icons on rooms in the room list https://github.com/matrix-org/matrix-react-sdk/pull/12343
- [x] Notification badge colors https://github.com/matrix-org/matrix-react-sdk/pull/12343
- [x] Room sublist text colors https://github.com/matrix-org/matrix-react-sdk/pull/12343
- [x] Primary buttons should use primary colors rather than accent colors https://github.com/matrix-org/matrix-react-sdk/pull/12299
- [x] Form controls should use the new accent background tokens https://github.com/matrix-org/matrix-react-sdk/pull/12299
- [x] Verification shield colors https://github.com/matrix-org/matrix-react-sdk/pull/12343
- [x] Editing stroke color https://github.com/matrix-org/matrix-react-sdk/pull/12299
- [x] Date separators https://github.com/matrix-org/matrix-react-sdk/pull/12343
```

**Comment by kongo09** [comment]
As I'm in discussion with Nad about https://github.com/element-hq/element-internal/issues/536 I'd like to make sure that we're not creating / implementing facts before there is a clear direction.

**Comment by robintown** [comment]
Interesting, that discussion would primarily bring https://github.com/matrix-org/matrix-react-sdk/pull/12241 in question, which changes our green actions to be black and white. Do we need to revert that change? The retainer work package linked to this issue would then likely become blocked on https://github.com/element-hq/element-internal/issues/536, for the record.

@gaelledel Do you have thoughts on how we should proceed?

**Comment by kongo09** [comment]
I think this requires guidance and alignment with @nadonomy
