### ISSUE TITLE
Roll out of Rust crypto stack

### ISSUE THREAD

**Issue by BillCarsonFr** [element-hq/element-web#27001]
## Rollout phase 1: new logins

- [x] New Logins on rust sdk by default - EW release 02/20 - [1.11.58](https://github.com/element-hq/element-web/releases/tag/v1.11.58)

## Rollout phase 2: migration of existing sessions on `app.element.io` and Element Desktop

~~Notice that the change will land in RC 1 week before the release on staging.~~

- [x] #27002
- [x] #27284 (EW 2024-05-01, ED 1.11.67 released 2024-05-22)
- [x] https://github.com/element-hq/element-web/issues/27490 (EW 2024-06-06, ED 1.11.69 released 2024-06-18)
- [x] Migrate 100% of existing users Target Date: EW/ED release  2024-07-08)

## Rollout phase 3: migration of existing sessions on all element deployments

- [x] #27560 Change the default for all Element deployments. Target: 1.11.70 RC 2024-06-25, release 2024-07-08)

**Comment by BillCarsonFr** [comment]
Created a new label Z-Element-R-Rollout-Blocker if an issue is discovered

**Comment by t3chguy** [comment]
@BillCarsonFr the canonical source for labels is a YAML file, otherwise it'll be deleted by the automation.

**Comment by BillCarsonFr** [comment]
> @BillCarsonFr the canonical source for labels is a [YAML fil](https://github.com/element-hq/element-web/blob/develop/.github/labels.yml)e, otherwise it'll be deleted by the automation.

Ok I think we can just re-use the existing Z-Element-R-Blocker then? As it won't be used anymore

**Comment by richvdh** [comment]
>  Notice that the change will land in RC 1 week before the release on staging.

This is incorrect (unless we deliberately make it so). `config.json` changes are independent of releases.

**Comment by richvdh** [comment]
I'm going to reopen this until the rollout actually happens (and we have migrated all users on app.element.io to rust)

**Comment by murlock1000** [comment]
The recent migration of element-web to the new rust crypto system without supporting MSC3061 has broken some of systems that relied on this feature. Specifically, the functionality where a bot would invite whitelisted users to a room and share room keys with them so they could see historic messages.

What is the current solution for an automated system that invites users to a room with existing messages and enables them to see historic messages now?

**Comment by richvdh** [comment]
IT'S DONE
