### ISSUE TITLE
Force devices to be verified

### ISSUE THREAD

**Issue by BillCarsonFr** [element-hq/element-web#28464]
Part of the [Trust And Decoration v2](https://github.com/element-hq/crypto-internal/issues/282) work.

## Context

We will soon ignore devices not signed by their users when encrypting and decrypting room events.
As a consequence a non verified device will not be able to participate in an encrypted room (will not receive room keys, and room keys sent will be ignored).

Currently it is optional to verify your device on login, the flow can be skipped. We want it to be non-skippable now in preparation for the future change.
<img width="621" alt="image" src="https://github.com/element-hq/crypto-barge/assets/9841565/2fd6a04b-cd19-4b6d-b64b-5e2edef1ed07">

## Breakdown

- [x] element-hq/crypto-internal#285 
- [ ] element-hq/crypto-internal#305

Later:
- [x] element-hq/crypto-internal#286

**Comment by uhoreg** [comment]
From the unit tests that, it looks like there are some cases to consider:  Currently, it does not prompt the user to verify if

- they are not in any encrypted rooms.  I assume that this will no longer be the case -- we'll want all users to verify even if they are not in any encrypted rooms.
- the client does not support encryption.  There isn't much we can do in this situation, so we'll probably keep this
- the server does not support cross-signing.  Cross-signing was introduced *ages* ago, so I don't know how much we care about such servers.
