### ISSUE TITLE
[Epic] Simplified Sliding Sync in Element Web

### ISSUE THREAD

**Issue by dbkr** [element-hq/element-web#28736]
### Your use case

New, updated tracker issue for simplified sliding sync as the old one was… old, and referred to regular sliding sync.

js-sdk PR: https://github.com/matrix-org/matrix-js-sdk/pull/4400/
web PR: https://github.com/element-hq/element-web/pull/28515

* [x] Adapt current sliding sync impl to new SSS (PoC version)
* [ ] Get tests passing on SSS PRs
* [ ] Get SSS PR merged (at this point we have SSS in labs replacing the old SS labs flag. Knocking and presence will not work if the labs flag is enabled).
* [ ] Get knocking working
  * May require support in synapse
  * How much work is this?
* [ ] Get presence working
  * May require support in synapse
  * How much work is this?
* [ ] Any other unknown unknowns that need fixing with the SSS experience
* [ ] Make SSS auto detect server support and fall back to regular sync v2
* [ ] De-labs!
* [ ] (probably significantly later) Remove sync v2 support

More detail to come as I explore what's needed for the various parts.

**Comment by paboum** [comment]
I would suggest starting from this:
![image](https://github.com/user-attachments/assets/00a706bb-4c1c-49b1-ba0c-d0fc8cd24a13)
The message is confusing as this is Element Web that does *not* support the current SS protocol (Synapse already has SSS since 1.114). Instead, this could be renamed to SS v1 or legacy SS.

**Comment by t3chguy** [comment]
@paboum EW supports Sliding Sync, it doesn't support an entirely different MSC called Simplified Sliding Sync, neither is v2 nor legacy. Both are distinct MSCs.
